[project]
name = "09-triangular-cluster"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Bjarte Johansen", email = "bjajoh@equinor.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
09-triangular-cluster = "09_triangular_cluster:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
